export const fields = [
  { name: "fecha", label: "Fecha", type: "text", required: true },
  {
    name: "productorProveedor",
    label: "Productor/Proveedor",
    type: "text",
    required: true,
  },
  {
    name: "kgIngresados",
    label: "KG Ingresados",
    type: "text",
    required: true,
  },
  { name: "producto", label: "Producto", type: "text", required: true },
  { name: "variedad", label: "Variedad", type: "text", required: true },
  { name: "numIngreso", label: "N° Ingreso", type: "text", required: true },
  { name: "exportador", label: "Exportador", type: "text", required: true },
  { name: "responsable", label: "Responsable", type: "text", required: true },
  {
    name: "bandJabas",
    label: "Bandejas/Jabas",
    type: "text",
    required: true,
  },
  { name: "numPallet", label: "N° Pallet", type: "text", required: true },
  {
    name: "trazRecepcion",
    label: "Trazabilidad Recepcion",
    type: "text",
    required: true,
  },
  {
    name: "fechaProceso",
    label: "Fecha de Proceso",
    type: "text",
    required: true,
  },
  {
    name: "pesoJabaBandeja",
    label: "Peso Jaba/Bandeja",
    type: "text",
    required: true,
  },
  { name: "firma", label: "Firma", type: "text", required: false },
  {
    name: "obs",
    label: "Observaciones",
    type: "text",
    required: false,
  },
  {
    name: "registroMateriaPrimaId",
    label: "Lote asociado",
    type: "select",
    required: true,
    options: (fields) =>
      fields.dynamic.registros.map((r) => ({
        label: r.nombreLote || `Lote #${r.id}`,
        value: r.id,
      })),
  },
  {
    name: "chequeos",
    type: "radioGroup",
    required: true,
    fullRow: true,
    options: ["Materia Prima", "Fruta Rechazada", "Descarte"],
  },
];
