export const fields = [
  { name: "fecha", label: "fecha", type: "text", required: true },
  {
    name: "prodProv",
    label: "Productor/Proveedor",
    type: "text",
    required: true,
  },
  {
    name: "kgIng",
    label: "KG Ingresados",
    type: "text",
    required: true,
  },
  { name: "producto", label: "Producto", type: "text", required: true },
  { name: "variedad", label: "Variedad", type: "text", required: true },
  { name: "numIng", label: "N° Ingreso", type: "text", required: true },
  { name: "exportador", label: "Exportador", type: "text", required: true },
  { name: "responsable", label: "Responsable", type: "text", required: true },
  {
    name: "bandJabas",
    label: "Bandejas/Jabas",
    type: "text",
    required: true,
  },
  { name: "numPallet", label: "N° Pallet", type: "text", required: true },
  {
    name: "trazRecep",
    label: "Trazabilidad Recepcion",
    type: "text",
    required: true,
  },
  {
    name: "fechaProceso",
    label: "Fecha de Proceso",
    type: "text",
    required: true,
  },
  {
    name: "pesoJabaBand",
    label: "Peso Jaba/Bandeja",
    type: "text",
    required: true,
  },
  { name: "firma", label: "Firma", type: "text", required: false },
  {
    name: "descargado",
    label: "Descargado por",
    type: "text",
    required: false,
  },
  {
    name: "detServ",
    label: "Detalle servicio",
    type: "text",
    required: false,
  },
  {
    name: "obs",
    label: "Observaciones",
    type: "text",
    required: false,
  },
  {
    name: "chequeos",
    type: "radioGroup",
    required: true,
    fullRow: true,
    options: ["Materia Prima", "Fruta Rechazada", "Descarte"],
  },
];
