export const fields = [
  { name: "fecha", label: "fecha", type: "text", required: true },
  {
    name: "productor/proveedor",
    label: "Productor/Proveedor",
    type: "text",
    required: true,
  },
  {
    name: "kg ingresados",
    label: "KG Ingresados",
    type: "text",
    required: true,
  },
  { name: "producto", label: "Producto", type: "text", required: true },
  { name: "variedad", label: "Variedad", type: "text", required: true },
  {
    name: "codigo de productor",
    label: "Codigo de productor",
    type: "text",
    required: true,
  },
  { name: "n° ingreso", label: "N° Ingreso", type: "text", required: true },
  { name: "exportador", label: "Exportador", type: "text", required: true },
  { name: "responsable", label: "Responsable", type: "text", required: true },
  {
    name: "bandejas/jabas",
    label: "Bandejas/Jabas",
    type: "text",
    required: true,
  },
  { name: "n° pallet", label: "N° Pallet", type: "text", required: true },
  {
    name: "trazabilidad recepcion",
    label: "Trazabilidad Recepcion",
    type: "text",
    required: true,
  },
  {
    name: "fecha de proceso",
    label: "Fecha de Proceso",
    type: "text",
    required: true,
  },
  {
    name: "peso jaba/bandeja",
    label: "Peso Jaba/Bandeja",
    type: "text",
    required: true,
  },
  { name: "firma", label: "Firma", type: "text", required: false },
  {
    name: "observaciones",
    label: "Observaciones",
    type: "text",
    required: true,
  },
  {
    name: "chequeos",
    type: "radioGroup",
    required: true,
    fullRow: true,
    options: ["Materia Prima", "Fruta Rechazada", "Descarte"],
  },
];
