export const fields = [
  {
    name: "dirReferencia",
    label: "Dirección de referencia",
    type: "text",
    required: true,
  },
  { name: "placa", label: "Placa", type: "text", required: true },
  { name: "placa2", label: "Placa2", type: "text", required: false },
  {
    name: "horaDescarga",
    label: "Hora de descarga",
    type: "datetime-local",
    required: true,
  },
  {
    name: "codNumero",
    label: "Código de número",
    type: "text",
    required: true,
  },
  {
    name: "campaña",
    label: "Campaña",
    type: "text",
    required: true,
  },
  { name: "exportador", label: "Exportador", type: "text", required: true },
  {
    name: "numSemana",
    label: "Número de semana",
    type: "text",
    required: true,
  },
  {
    name: "ordenVolcado",
    label: "Orden de volcado",
    type: "text",
    required: false,
  },
  {
    name: "fechaRecepcion",
    label: "Fecha de recepción",
    type: "date",
    required: true,
  },
  {
    name: "fechaGuia",
    label: "Fecha de guía",
    type: "date",
    required: false,
  },
  {
    name: "guiaProductor",
    label: "Guía Productor",
    type: "text",
    required: true,
  },
  {
    name: "guiaSenasa",
    label: "Guía SENASA",
    type: "text",
    required: false,
  },
  {
    name: "guiaTransportista",
    label: "Guia Transportista",
    type: "text",
    required: true,
  },
  {
    name: "glosa",
    label: "Glosa",
    type: "text",
    required: true,
  },
  {
    name: "productorProveedor",
    label: "Productor-Proveedor",
    type: "text",
    required: true,
  },
  {
    name: "codigo",
    label: "Código",
    type: "text",
    required: true,
  },
  {
    name: "numIngreso",
    label: "Número de ingreso",
    type: "text",
    required: true,
  },
  { name: "clp", label: "CLP", type: "text", required: true },
  { name: "pesoNeto", label: "Peso neto", type: "text", required: true },
  {
    name: "cantJabas",
    label: "Cantidad de jabas",
    type: "text",
    required: true,
  },
  {
    name: "pesoDescuento",
    label: "Peso descuento",
    type: "text",
    required: false,
  },
  {
    name: "pesoGuia",
    label: "Peso según Guía",
    type: "text",
    required: true,
  },
  {
    name: "difPeso",
    label: "Diferencia de peso",
    type: "text",
    required: true,
  },
  {
    name: "responsable",
    label: "Responsable",
    type: "text",
    required: true,
  },
  {
    name: "empTransportes",
    label: "Empresa de Transporte",
    type: "text",
    required: true,
  },
  { name: "chofer", label: "Chofer", type: "text", required: true },
  {
    name: "licConducir",
    label: "Licencia de conducir",
    type: "text",
    required: true,
  },
  {
    name: "obs",
    label: "Observaciones",
    type: "text",
    required: false,
  },
  {
    name: "descargado",
    label: "Operario de descarga",
    type: "text",
    required: false,
  },
  {
    name: "detServicio",
    label: "Detalle servicio",
    type: "text",
    required: false,
  },
];
