export const fields = [
  { name: "placa", label: "Placa", type: "text", required: true },
  {
    name: "horaDesc",
    label: "Hora de descarga",
    type: "text",
    required: true,
  },
  { name: "exportador", label: "Exportador", type: "text", required: true },
  { name: "numSemana", label: "# Semana", type: "text", required: true },
  {
    name: "ordenVolc",
    label: "Orden de volcado",
    type: "text",
    required: true,
  },
  {
    name: "fechaRecep",
    label: "Fecha de recepción",
    type: "text",
    required: true,
  },
  {
    name: "guiaProd",
    label: "Guía Productor",
    type: "text",
    required: true,
  },
  {
    name: "prodProv",
    label: "Productor-Proveedor",
    type: "text",
    required: true,
  },
  {
    name: "codLote",
    label: "Codigo de lote",
    type: "text",
    required: true,
  },
  { name: "clp", label: "CLP", type: "text", required: true },
  { name: "pesoNeto", label: "Peso neto", type: "text", required: true },
  {
    name: "cantJabas",
    label: "Cantidad de jabas",
    type: "text",
    required: true,
  },
  {
    name: "pesoDesc",
    label: "Peso descuento",
    type: "text",
    required: true,
  },
  {
    name: "difPeso",
    label: "Diferencia de peso",
    type: "text",
    required: true,
  },
  {
    name: "empTrans",
    label: "Empresa de Transporte",
    type: "text",
    required: true,
  },
  { name: "chofer", label: "Chofer", type: "text", required: false },
  {
    name: "licCond",
    label: "Licencia de conducir",
    type: "text",
    required: true,
  },
  {
    name: "obs",
    label: "Observaciones",
    type: "text",
    required: false,
  },
];
