export const fields = [
  { name: "placa", label: "Placa", type: "text", required: true },
  {
    name: "hora de descarga",
    label: "Hora de descarga",
    type: "text",
    required: true,
  },
  { name: "exportador", label: "Exportador", type: "text", required: true },
  { name: "# semana", label: "# Semana", type: "text", required: true },
  {
    name: "orden de volcado",
    label: "Orden de volcado",
    type: "text",
    required: true,
  },
  {
    name: "fecha de recepción",
    label: "Fecha de recepción",
    type: "text",
    required: true,
  },
  {
    name: "guia productor",
    label: "Guía Productor",
    type: "text",
    required: true,
  },
  {
    name: "productor-proveedor",
    label: "Productor-Proveedor",
    type: "text",
    required: true,
  },
  {
    name: "codigo de lote",
    label: "Codigo de lote",
    type: "text",
    required: true,
  },
  { name: "clp", label: "CLP", type: "text", required: true },
  { name: "peso neto", label: "Peso neto", type: "text", required: true },
  {
    name: "cantidad de jabas",
    label: "Cantidad de jabas",
    type: "text",
    required: true,
  },
  {
    name: "peso descuento",
    label: "Peso descuento",
    type: "text",
    required: true,
  },
  {
    name: "diferencia de peso",
    label: "Diferencia de peso",
    type: "text",
    required: true,
  },
  {
    name: "empresa de transporte",
    label: "Empresa de Transporte",
    type: "text",
    required: true,
  },
  { name: "chofer", label: "Chofer", type: "text", required: false },
  {
    name: "licencia de conducir",
    label: "Licencia de conducir",
    type: "text",
    required: true,
  },
  {
    name: "observaciones",
    label: "Observaciones",
    type: "text",
    required: false,
  },
  { name: "observador", label: "Observador", type: "text", required: false },
];
