export const fields = [
    {
      name: "cliente",
      label: "Cliente",
      type: "text",
      required: "true",
    },
    {
      name: "fecha",
      label: "Fecha",
      type: "text",
      required: "true",
    },
    {
      name: "nrContenedor",
      label: "N°Contenedor",
      type: "text",
      required: "true",
    },
    {
      name: "puntosCheck",
      label: "Puntos chequeados:",
      required: true,
      type: "checkboxGroup",
      options: ["1", "2", "3", "4", "5"],
    },
    {
      name: "inspector",
      label: "Inspector",
      type: "text",
      required: "true",
    },
    {
      type: "sectionTitle",
      label: "1. Verificación de contenedor en rampa",
    },
    {
      name: "contenedorLimp",
      label: "Contenedor limpio",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"],
    },
    {
      name: "roturasContenedor",
      label: "Roturas internas del contenedor",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"],
    },
    {
      name: "obs",
      label: "Obs",
      type: "text",
      required: false,
    },
    {
      type: "sectionTitle",
      label: "2. Documento que acompañan al contenedor",
    },
    {
      name: "precintos",
      label: "Precintos",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"],
    },
    {
      name: "cortinAire",
      label: "Cortina de aire",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"],
    },
    {
      name: "termoRegistro",
      label: "Termo registro",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"],
    },
    {
      type: "sectionTitle",
      label: "3. Identificación correcta del envío",
    },
    {
      name: "trazabilidadComp",
      label: "Etiquetas de trazabilidad completa",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"],
    },
    {
      name: "palletsComp",
      label: "Etiquetas de pallets completas",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"],
    },
    {
      type: "palletBlock",
      label: "Distribución de Pallets",
    },
    {
      type: "sectionTitle",
      label: "4. Entrega y logística"
    },
    {
      name: "documentacionComp",
      label: "Entrega de documentacion completa",
      type: "radioGroup",
      required: true,
      options: ["SI", "NO", "N/A"]
    },
    {
      name: "hInicial",
      label: "Hora inicial",
      type: "text",
      required: true,
    },
    {
      name: "hFinal",
      label: "Hora final ",
      type: "text",
      required: true,
    },
    {
      name: "precintOPlanta",
      label: "Precinto Planta",
      type: "text",
      required: false,
    },
    {
      name: "precintoAduana",
      label: "Precinto Aduana",
      type: "text",
      required: false,
    },
    {
      name: "precintoLinea",
      label: "Precinto Linea",
      type: "text",
      required: false,
    },
  ];